/*
8 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package au.edu.rmit.sef.view;

import au.edu.rmit.sef.model.Point;
import au.edu.rmit.sef.ulti.SEFConstant;
import au.edu.rmit.sef.ulti.UtilityFunction;

/**
 *
 * @author Khang
 */
public class Screen5 extends javax.swing.JPanel {
    private BoardPanel boardPanel;
    private Board squareBoard;
    /**
     * Creates new form GameScreen
     */
    public Screen5() {
        initComponents();
        addCustomComponent();
    }
    private void addCustomComponent() {
		squareBoard = new Board(SEFConstant.NUM_ROW,SEFConstant.NUM_COL);
		boardPanel = new BoardPanel(squareBoard);
		jPanel1.add(boardPanel);
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        newButton = new javax.swing.JLabel();
        quitButton = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        noplayerLabel = new javax.swing.JLabel();
        playernameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        noroundLabel = new javax.swing.JLabel();
        traceButton = new javax.swing.JLabel();
        guessButton = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newButton.PNG"))); // NOI18N

        quitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quitButton.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        noplayerLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        noplayerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no_player2.PNG"))); // NOI18N

        playernameLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        playernameLabel.setText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roundLabel.PNG"))); // NOI18N

        noroundLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        noroundLabel.setText("0");
        noroundLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        traceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traceButton.PNG"))); // NOI18N

        guessButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guessButton.PNG"))); // NOI18N

        unitLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        unitLabel.setText("* units");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noplayerLabel)
                .addGap(18, 18, 18)
                .addComponent(playernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(unitLabel)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(newButton)
                .addGap(68, 68, 68)
                .addComponent(traceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guessButton)
                .addGap(100, 100, 100)
                .addComponent(quitButton)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(noplayerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel1))
                    .addComponent(noroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(unitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(traceButton)
                            .addComponent(newButton)
                            .addComponent(guessButton))))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>                        

    public void renew(){
    	for(int i = 0; i < squareBoard.getNumRow() - 1; i ++){
    		for(int j = 0; j < squareBoard.getNumCol() -1; j++){
    			UtilityFunction.setColorForCell(squareBoard, new Point(i, j), SEFConstant.CellColorInt.WHITE_BG);
    		}
    	}
    	playernameLabel.setText("");
    	unitLabel.setText("* unit");
    }
    public BoardPanel getBoardPanel() {
		return boardPanel;
	}
	public void setBoardPanel(BoardPanel boardPanel) {
		this.boardPanel = boardPanel;
	}
	public Board getSquareBoard() {
		return squareBoard;
	}
	public void setSquareBoard(Board squareBoard) {
		this.squareBoard = squareBoard;
	}
	public javax.swing.JLabel getGuessButton() {
		return guessButton;
	}
	public void setGuessButton(javax.swing.JLabel guessButton) {
		this.guessButton = guessButton;
	}
	public javax.swing.JLabel getNewButton() {
		return newButton;
	}
	public void setNewButton(javax.swing.JLabel newButton) {
		this.newButton = newButton;
	}
	public javax.swing.JLabel getNoplayerLabel() {
		return noplayerLabel;
	}
	public void setNoplayerLabel(javax.swing.JLabel noplayerLabel) {
		this.noplayerLabel = noplayerLabel;
	}
	public javax.swing.JLabel getNoroundLabel() {
		return noroundLabel;
	}
	public void setNoroundLabel(javax.swing.JLabel noroundLabel) {
		this.noroundLabel = noroundLabel;
	}
	public javax.swing.JLabel getQuitButton() {
		return quitButton;
	}
	public void setQuitButton(javax.swing.JLabel quitButton) {
		this.quitButton = quitButton;
	}
	public javax.swing.JLabel getTraceButton() {
		return traceButton;
	}
	public void setTraceButton(javax.swing.JLabel traceButton) {
		this.traceButton = traceButton;
	}
	public javax.swing.JLabel getUnitLabel() {
		return unitLabel;
	}
	public void setUnitLabel(javax.swing.JLabel unitLabel) {
		this.unitLabel = unitLabel;
	}
	
	
	public javax.swing.JLabel getPlayernameLabel() {
		return playernameLabel;
	}
	public void setPlayernameLabel(javax.swing.JLabel playernameLabel) {
		this.playernameLabel = playernameLabel;
	}


	// Variables declaration - do not modify   
	private javax.swing.JLabel playernameLabel;
    private javax.swing.JLabel guessButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newButton;
    private javax.swing.JLabel noplayerLabel;
    private javax.swing.JLabel noroundLabel;
    private javax.swing.JLabel quitButton;
    private javax.swing.JLabel traceButton;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration                   
}
