/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package au.edu.rmit.sef.view;

/**
 *
 * @author Khang
 */
public class Screen2 extends javax.swing.JPanel {

    /**
     * Creates new form Screen1
     */
    public Screen2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        player2Button = new javax.swing.JLabel();
        player3Button = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        addshapeButton = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.PNG"))); // NOI18N

        player2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2playerButton.PNG"))); // NOI18N

        player3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3playerButton.PNG"))); // NOI18N

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backButton.PNG"))); // NOI18N
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addshapeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addshapeButton.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(player3Button)
                                    .addComponent(player2Button)
                                    .addComponent(addshapeButton))))
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 538, Short.MAX_VALUE)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(player2Button)
                .addGap(26, 26, 26)
                .addComponent(player3Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(addshapeButton)
                .addGap(20, 20, 20)
                .addComponent(backButton)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>                        


    public javax.swing.JLabel getAddshapeButton() {
		return addshapeButton;
	}

	public void setAddshapeButton(javax.swing.JLabel addshapeButton) {
		this.addshapeButton = addshapeButton;
	}

	public javax.swing.JLabel getBackButton() {
		return backButton;
	}

	public void setBackButton(javax.swing.JLabel backButton) {
		this.backButton = backButton;
	}

	public javax.swing.JLabel getPlayer2Button() {
		return player2Button;
	}

	public void setPlayer2Button(javax.swing.JLabel player2Button) {
		this.player2Button = player2Button;
	}

	public javax.swing.JLabel getPlayer3Button() {
		return player3Button;
	}

	public void setPlayer3Button(javax.swing.JLabel player3Button) {
		this.player3Button = player3Button;
	}


	// Variables declaration - do not modify                     
    private javax.swing.JLabel addshapeButton;
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel player2Button;
    private javax.swing.JLabel player3Button;
    // End of variables declaration                   
}
